included:
  - DinoHome
  - DinoHomeTests

excluded:
  - .build
  - DerivedData

opt_in_rules:
  - empty_count
  - force_unwrapping

line_length:
  warning: 120
  error: 160

identifier_name:
  min_length:
    warning: 2
